version: '3'
services:

  rs1_1:
      hostname: rs1_1
      image: $MONGODB_IMAGE
      restart: always
      command: mongod --port 27017 --replSet rs1
      volumes:
      - ./volumes/rs1_1:/data/db
      networks:
      - mongo
  rs1_2:
      hostname: rs1_2
      image: $MONGODB_IMAGE
      restart: always
      command: mongod --port 27017 --replSet rs1
      volumes:
      - ./volumes/rs1_2:/data/db
      networks:
      - mongo
  rs1_3:
      hostname: rs1_3
      image: $MONGODB_IMAGE
      restart: always
      command: mongod --port 27017 --replSet rs1
      volumes:
      - ./volumes/rs1_3:/data/db
      networks:
      - mongo

networks:
  mongo: